# Generated by Django 5.1.5 on 2025-01-22 18:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('USA', 'Estados Unidos'), ('BRA', 'Brasil'), ('CAN', 'Canadá'), ('MEX', 'México'), ('ARG', 'Argentina'), ('CHL', 'Chile'), ('COL', 'Colômbia'), ('PER', 'Peru'), ('VEN', 'Venezuela'), ('URY', 'Uruguai'), ('FRA', 'França'), ('DEU', 'Alemanha'), ('ITA', 'Itália'), ('ESP', 'Espanha'), ('PRT', 'Portugal'), ('NLD', 'Países Baixos (Holanda)'), ('BEL', 'Bélgica'), ('CHE', 'Suíça'), ('AUT', 'Áustria'), ('SWE', 'Suécia'), ('NOR', 'Noruega'), ('DNK', 'Dinamarca'), ('FIN', 'Finlândia'), ('POL', 'Polônia'), ('CZE', 'República Tcheca'), ('HUN', 'Hungria'), ('GRC', 'Grécia'), ('JPN', 'Japão'), ('CHN', 'China'), ('IND', 'Índia'), ('PAK', 'Paquistão'), ('IDN', 'Indonésia'), ('PHL', 'Filipinas'), ('RUS', 'Rússia'), ('AUS', 'Austrália'), ('NZL', 'Nova Zelândia'), ('ZAF', 'África do Sul'), ('EGY', 'Egito'), ('NGA', 'Nigéria'), ('KEN', 'Quênia'), ('ETH', 'Etiópia'), ('TUR', 'Turquia'), ('KOR', 'Coreia do Sul'), ('SAU', 'Arábia Saudita'), ('ISR', 'Israel'), ('GBR', 'Reino Unido'), ('IRL', 'Irlanda'), ('THA', 'Tailândia'), ('VNM', 'Vietnã'), ('SGP', 'Singapura'), ('MYS', 'Malásia')], max_length=100, null=True)),
            ],
        ),
    ]
